version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      day: "monday"
    commit-message:
      prefix: "npm"
    versioning-strategy: widen
    open-pull-requests-limit: 1000000000000000000000000
