version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Europe/Madrid"
    commit-message:
      prefix: "npm"
    versioning-strategy: widen
    open-pull-requests-limit: 1000000000000000000000000
    assignees:
      - "elPandaFriki"
    "reviewers":
      - "elPandaFiki"
    "labels":
      - "npm"
      - "dependencies"
    
