name: 'Deploy'
on:
    workflow_run:
        workflows: ['Tests']
        types:
            - completed
        branches: ['master']
permissions: write-all
jobs:
    on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - run: echo 'Tests have failed. Can not generate new build.'
    build:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - name: Start Notification
              run: echo 'Tests have conclused successfully. Generating new build...'
            - name: Set repository to latest commit
              uses: actions/checkout@v3
            - name: Set up Node.js environment to version ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm install
            - name: Build React app
              run: npm run build
            - name: Setup Pages
              uses: actions/configure-pages@v3
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                path: './build'
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
            - name: End Notification
              run: echo 'Build have concluded successfully.'
