name: 'Deploy'
on:
    workflow_run:
        workflows: ['Tests']
        types:
            - completed
        branches: ['master']
jobs:
    on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - run: echo 'Tests have failed. Can not generate new build.'
    build:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - name: Start Notification
              run: echo 'Tests have conclused successfully. Generating new build...'
            - name: Set repository to latest commit
              uses: actions/checkout@v3
            - name: Set up Node.js environment to version ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm install
            - name: Build React app
              run: npm run build
            - name: Deploy to GitHub Pages
              run: |
                  git config --global user.name ${user_name}
                  git config --global user.email ${user_email}
                  git remote set-url origin https://${github_token}@github.com/${repository}
                  npm run deploy_to_github_pages
              env:
                  user_name: 'github-actions[bot]'
                  user_email: 'github-actions[bot]@users.noreply.github.com'
                  github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
                  repository: ${{ github.repository }}
            - name: End Notification
              run: echo 'Build have concluded successfully.'
